# Generated by Django 4.1.2 on 2022-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mpg", models.FloatField()),
                ("cyl", models.IntegerField()),
                ("disp", models.FloatField()),
                ("hp", models.IntegerField()),
                ("drat", models.FloatField()),
                ("wt", models.FloatField()),
                ("qsec", models.FloatField()),
                ("vs", models.IntegerField()),
                ("am", models.IntegerField()),
                ("gear", models.IntegerField()),
                ("carb", models.IntegerField()),
            ],
        ),
    ]
