# Generated by Django 4.1.2 on 2022-10-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
